name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
      - cron: '31 1 * * *'
    # - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 7
          STOP_AT_OTHER: true
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          COMMITTER_NAME: GitHubActionBot
          AUTHOR_NAME: Victor Hugo Simões
          AUTHOR_EMAIL: victorhugobs@eq.ufrj.br
